# Generated by Django 5.0.6 on 2024-06-21 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='tprice',
            field=models.IntegerField(default=0),
        ),
    ]
