# Generated by Django 5.0.6 on 2024-06-25 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapp', '0002_alter_cart_count_alter_cart_tprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproduct',
            name='crt',
            field=models.IntegerField(default=0),
        ),
    ]
