# Generated by Django 5.0.6 on 2024-07-02 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vapp', '0004_alter_cart_cartitm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addproduct',
            name='crt',
        ),
    ]
