# Generated by Django 5.0.6 on 2024-07-03 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapp', '0005_remove_addproduct_crt'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
