# Generated by Django 5.0.6 on 2024-07-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapp', '0006_farmer_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=1500)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(default='users@gmail.com', max_length=254)),
            ],
        ),
    ]
