# Generated by Django 5.0.6 on 2024-07-03 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vapp', '0007_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='comment',
            new_name='feedback',
        ),
    ]
