# Generated by Django 5.0.6 on 2024-07-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapp', '0008_rename_comment_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
