# Generated by Django 5.0.6 on 2024-07-04 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapp', '0009_alter_farmer_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0)),
                ('datee', models.DateTimeField(auto_now=True)),
                ('totprice', models.IntegerField(default=0)),
                ('buyitm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vapp.addproduct')),
                ('userdetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vapp.user')),
            ],
        ),
    ]
