# Generated by Django 5.0.6 on 2024-07-05 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapp', '0011_alter_buy_buyitm'),
    ]

    operations = [
        migrations.CreateModel(
            name='cont',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('email', models.EmailField(default='users@gmail.com', max_length=254)),
                ('phonenumber', models.IntegerField()),
                ('message', models.CharField(max_length=1500)),
            ],
        ),
    ]
