# Generated by Django 5.0.6 on 2024-07-08 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapp', '0012_cont'),
    ]

    operations = [
        migrations.CreateModel(
            name='rply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1500)),
                ('name', models.CharField(max_length=15)),
                ('email', models.EmailField(default='users@gmail.com', max_length=254)),
            ],
        ),
    ]
