# Generated by Django 5.0.6 on 2024-07-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapp', '0014_remove_cont_email_remove_cont_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cont',
            name='email',
            field=models.EmailField(default='users@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='cont',
            name='name',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cont',
            name='phonenumber',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
