# Generated by Django 5.0.6 on 2024-07-08 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vapp', '0017_cont_email_cont_name_cont_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cont',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cont',
            name='name',
        ),
        migrations.RemoveField(
            model_name='cont',
            name='phonenumber',
        ),
    ]
