# Generated by Django 5.0.6 on 2024-07-12 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapp', '0018_remove_cont_email_remove_cont_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='email',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='name',
        ),
        migrations.AddField(
            model_name='cont',
            name='frdetail',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vapp.farmer'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='fdetail',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vapp.farmer'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='udetail',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vapp.user'),
            preserve_default=False,
        ),
    ]
