# Generated by Django 5.0.6 on 2024-07-25 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapp', '0024_cartpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartpayment',
            name='cartuser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vapp.user'),
            preserve_default=False,
        ),
    ]
