# Generated by Django 5.0.6 on 2024-08-10 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapp', '0027_addproduct_stock_alter_cartpayment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='deliverystatus',
            field=models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
    ]
